### ISSUE TITLE
caffe cannot build

### ISSUE THREAD

**Issue by xxy90** [ZhiwenShao/JAANet#2]
After I merged  "src" and "include" into the official Caffe, the official caffe cannot build. I get the error that 
 PoolingParameter_RoundMode does not name a type  PoolingParameter_RoundMode round_mode_

**Comment by ZhiwenShao** [comment]
Please refer to https://github.com/BVLC/caffe/issues/6535. This problem is not relevant to our code.

**Comment by xxy90** [comment]
I'll try. Thank you!

**Comment by ttjack123** [comment]
> After I merged "src" and "include" into the official Caffe, the official caffe cannot build. I get the error that
> PoolingParameter_RoundMode does not name a type PoolingParameter_RoundMode round_mode_


I solved this by merging the following LayerParameter into caffe's original LayerParameter.

message LayerParameter {
	optional AUMaskBasedLandParameter au_mask_based_land_param = 1;
	optional DivisionParameter division_param = 2;
	optional CombinationParameter combination_param = 3;
	optional AlignDataTransformParameter align_data_transform_param = 4;
	optional DiceCoefLossParameter dice_coef_loss_param = 5;
}

I think this problem may come form redefinition of LayerParameter, since at the first time I just copy the above lines to the end of caffe.proto and the PoolingParameter_RoundMode error occurs and after 
I merging it to the original LayerParameter this error disappears.

**Comment by ZhiwenShao** [comment]
OK, great!
